### PR TITLE
fix!: remove console log and throw instead

### LINKED ISSUE #70: Remove console logging
We have console.log statements in the code! We should remove those.

### PR DESCRIPTION
**Pull request by JustinBeckwith**
BREAKING CHANGE: In previous releases of the library, invoking the `request` with a multipart upload, and no defined callback (consuming a stream) would result in unpredictable behavior.  The code would write to console, but the method would just return.  To make the behavior more explicit, the method will now throw if multipart uploads and no callback are provided. 

Fixes #70

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -192,8 +192,7 @@ function teenyRequest(
   const multipart = reqOpts.multipart as RequestPart[];
   if (reqOpts.multipart && multipart.length === 2) {
     if (!callback) {
-      console.error('multipart without callback not implemented.');
-      return;
+      throw new Error('multipart without callback not implemented.');
```
Comment (stephenplusplus) [inline src/index.ts]: The wording here tripped me up, but I believe this is a "TODO"/missing feature of the library. If that sounds right, could you either add in a "@TODO" here, or a new issue to request support for multipart uploads through streaming/promises?

**Comment by JustinBeckwith** [comment]
Good call both of you :) I flagged this as a breaking change, and I went ahead and added a TODO to call out the missing feature.
